[nixos]
precision-5680-2023-root ansible_host=precision-5680-2023 ansible_user=root
precision-5680-2023-nick ansible_host=precision-5680-2023 ansible_user=nick
xps13-nick ansible_host=xps13 ansible_user=nick
xps13-root ansible_host=xps13 ansible_user=root

[debian]
borg-host ansible_connection=local ansible_user=root
ai-host ansible_host=ai-host.lan ansible_user=root
scrooge-host ansible_host=scrooge-host.lan ansible_user=root
proxmox ansible_host=proxmox.lan ansible_user=root
document-host ansible_host=document-host.lan ansible_user=root
golden-host ansible_host=golden-host.lan ansible_user=root
earlgrey-hetzner-vps-1 ansible_host=earlgrey-hetzner-vps-1 ansible_user=root
earlgrey-hetzner-vps-2 ansible_host=earlgrey-hetzner-vps-2 ansible_user=root
earlgrey-hetzner-vps-3 ansible_host=earlgrey-hetzner-vps-3 ansible_user=root
proxy-host ansible_host=proxy-host.lan ansible_user=root

[non_proxmox]
earlgrey-hetzner-vps-1
earlgrey-hetzner-vps-2
earlgrey-hetzner-vps-3
precision-5680-2023-root
precision-5680-2023-nick
xps13-nick
xps13-root



